// <auto-generated />
//
// This file was automatically generated by PocosGenerator.csx, inspired from the PetaPoco T4 Template
// Do not make changes directly to this file - edit the PocosGenerator.GenerateClass() method in the PocosGenerator.Core.csx file instead
// 

using System;
using Dapper.Contrib.Extensions;
using System.Collections.Generic;

namespace AP_MediaService.DAL.Models.GenerateModels
{
  

    [Table("MSTMediaServerConfig")]
    public partial class MSTMediaServerConfig
    {
        [ExplicitKey]
        public Guid MediaServerConfigID { get; set; }
        public string MediaServerName { get; set; }
        public string MediaServerKey { get; set; }
        public string Endpoint { get; set; }
        public string AccessKey { get; set; }
        public string SecretKey { get; set; }
        public string PublicURL { get; set; }
        public string DefaultBucket { get; set; }
        public string TempBucket { get; set; }
        public bool? WithSSL { get; set; }
        public Guid StorageTypeID { get; set; }
        public Guid? CreatedByUserID { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid? ModifiedByUserID { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public bool? IsDeleted { get; set; }
        public Guid? DeleteByUserID { get; set; }
        public DateTime? DeleteDate { get; set; }
    }

    [Table("MSTStorageType")]
    public partial class MSTStorageType
    {
        [ExplicitKey]
        public Guid StorageTypeID { get; set; }
        public string StorageTypeName { get; set; }
        public string Key { get; set; }
        public bool IsActive { get; set; }
        public Guid? CreatedByUserID { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid? ModifiedByUserID { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public bool? IsDeleted { get; set; }
        public Guid? DeleteByUserID { get; set; }
        public DateTime? DeleteDate { get; set; }
    }
}
